#!/usr/bin/env python3
r"""
init_contracts.py — idempotent per-unit contract-stub generator (BOOKSMITH).

PURPOSE (KIT_ARCHITECTURE (c) init_contracts.py; LESSONS_LEDGER §2.3, §2.4)
    Generate one contracts/{unit_id}.md stub per unit from the seed's
    structural map, in ONE pass. Idempotent — won't overwrite an existing
    contract without --force. Every stub carries the interface-contract schema
    the writing loop reads (Authorship Class / Intent / Inherits / Must
    Accomplish / Must Plant / Must Callback / Delivers / Constraints / Scope /
    Length / Canon Anchors / Register Profile), with the fields left as
    [BO DRAFTS: ...] prompts for Phase-A seed construction.

    The key refactor from the source scripts: the unit list + authorship class
    are read from book_config.json, NOT hard-coded. The seed unit list is the
    ordered keys of book_config.authorship.per_chapter_overrides (each maps a
    unit_id -> class A/B/C). The unit noun (chapter vs part) comes from
    book_config.voice.unit_noun. NO book-specific value is hard-coded here.

CONTRACT
    python init_contracts.py --config book_config.json [--force]
                             [--root <workspace>] [--only <unit_id>]
        -> writes stubs to book_workspace/<slug>/contracts/ using the contract
           template (templates/contract.template.md if present, else a baked
           default) + the unit list. Won't overwrite without --force.

    Class discipline (LESSONS_LEDGER §2.4): the stub records the unit's
    authorship class and, for Class A, is written as contracts/{id}_outline.md
    (outline-only; the manuscript stays empty) — never a full prose contract.

SOURCE
    C:\\AI_BOOK\\_tools\\init_contracts.py (+ C:\\BOOK\\_tools\\init_contracts.py,
    C:\\BOOK-test3\\_tools\\init_contracts.py) — the hard-coded CHAPTERS array
    is replaced by config-derived units; the template + idempotency + --force +
    --only flow are preserved.
"""
import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
KIT_ROOT = SCRIPT_DIR.parent
TEMPLATE_CANDIDATES = [
    KIT_ROOT / "templates" / "contract.template.md",
]

CLASS_LABEL = {
    "A": "A (human-only — OUTLINE ONLY; manuscript stays empty until Bo writes it)",
    "B": "B (machine scaffold with [BO-WRITES: ...] markers on load-bearing passages)",
    "C": "C (machine drafts full first draft; Bo revises)",
}


# ─────────────────────────────────────────────────────────────────────────────
# Baked default template (used only if templates/contract.template.md is absent)
# Schema per LESSONS_LEDGER §2.3.
# ─────────────────────────────────────────────────────────────────────────────

DEFAULT_TEMPLATE = """# {unit_noun_cap} Contract — {unit_id}

*Generated by `_tools/init_contracts.py` on {date}. Stub v0.1 — fill during Phase-A seed construction. Append-only after the first draft.*

---

## Metadata

- **{unit_noun_cap} id:** {unit_id}
- **Order:** {order} of {total}
- **Title:** *[BO DRAFTS: {unit_noun} title]*
- **Authorship class:** {class_label}
- **Target words:** *[BO DRAFTS: target ± 20%]*
- **Register profile:** *[BO DRAFTS: brief characterization of voice/register for this {unit_noun}]*

---

## Intent

*[BO DRAFTS: One-paragraph Commander's Intent. What does this {unit_noun} accomplish and why does it exist in the arc?]*

---

## Inherits (entry state)

*[BO DRAFTS: What does the reader know / feel / believe on entry? Active concepts. Tension 1-10 at entry. Populated from the boundary state snapshot at writing time.]*

---

## Must Accomplish (3-7 verifiable)

*[BO DRAFTS: concrete, checkable requirements — one per line.]*

---

## Must Plant (seed -> specific payoff {unit_noun})

*[BO DRAFTS: seed -> target {unit_noun_lower}.]*

---

## Must Callback (<- specific source {unit_noun}; WITH VARIATION, never exact quotation)

*[BO DRAFTS: callback <- source {unit_noun_lower}. Exact quotation is the AI signature; vary the wording.]*

---

## Delivers (exit state)

*[BO DRAFTS: What does the reader know / feel / believe on exit? Populated as the boundary state snapshot.]*

---

## Constraints

*[BO DRAFTS: forbidden phrasings / anachronism guardrails / register limits / canon-wall rules.]*

---

## Scope

- **Autonomous:** draft into `manuscript/drafts/{unit_id}_v1.md`; self-assess; write handoff; update thread/dependency/refrain registries + state snapshot; run the auto-audit.
- **Escalate to Bo:** register drift; canon/continuity contradiction; anything that would change a Confirmed Decision.

---

## Length

*[BO DRAFTS: target word count ± 20%.]*

---

## Canon Anchors (derivation source; resolve to real files in `canon_refs/` — never cited by name in prose)

*[BO DRAFTS: canon_refs/ files this {unit_noun} derives from.]*

---

## Refrain Placement

*[BO DRAFTS: does the sacred refrain land in this {unit_noun}? At what exact wording / position?]*

---

## Adjacent contracts

- Prior: `contracts/{prev_id}.md`
- Next: `contracts/{next_id}.md`

---

*Contract v0.1 (stub) for {unit_id}. Generated {date}.*
"""


DEFAULT_OUTLINE_TEMPLATE = """# {unit_noun_cap} Outline — {unit_id}  (CLASS A — HUMAN-ONLY)

*Generated by `_tools/init_contracts.py` on {date}. This {unit_noun} is **Class A**: the harness produces an OUTLINE ONLY. The manuscript file (`manuscript/current/{unit_id}_current.md`) MUST stay empty until Bo writes it. Do NOT draft prose here — even a placeholder draft is a Class-A violation (LESSONS_LEDGER §2.4).*

---

## Metadata

- **{unit_noun_cap} id:** {unit_id}
- **Order:** {order} of {total}
- **Title:** *[BO DRAFTS]*
- **Authorship class:** {class_label}

---

## Intent (outline)

*[BO DRAFTS: one paragraph — what this {unit_noun} must do emotionally + structurally. This is the most load-bearing kind of unit; it is human-authored on purpose.]*

---

## Beats (outline only — NO prose)

*[BO DRAFTS: ordered beats / moments the {unit_noun} must hit. Bullet list of beats, not sentences of prose.]*

---

## Inherits (entry state)

*[BO DRAFTS: reader knows/feels/believes on entry.]*

---

## Delivers (exit state)

*[BO DRAFTS: reader knows/feels/believes on exit.]*

---

## Refrain / sacred-term placement

*[BO DRAFTS: exact wording + position if the refrain lands here.]*

---

## Adjacent contracts

- Prior: `contracts/{prev_id}.md`
- Next: `contracts/{next_id}.md`

---

*Class-A outline v0.1 for {unit_id}. Generated {date}. The manuscript stays empty until Bo authors it.*
"""


# ─────────────────────────────────────────────────────────────────────────────

def load_config(path: Path) -> dict:
    with path.open(encoding="utf-8") as fh:
        return json.load(fh)


def workspace_root(cfg: dict, config_path: Path, explicit_root) -> Path:
    if explicit_root:
        return Path(explicit_root)
    slug = cfg.get("slug")
    base = config_path.resolve().parent
    if slug:
        candidate = base / "book_workspace" / slug
        if candidate.exists() or (base / "book_workspace").exists():
            return base / "book_workspace" / slug
        if base.name == slug:
            return base
    return base


def load_template() -> str:
    for cand in TEMPLATE_CANDIDATES:
        if cand.exists():
            return cand.read_text(encoding="utf-8")
    return DEFAULT_TEMPLATE


def derive_units(cfg: dict) -> list:
    """The seed unit list = ordered keys of authorship.per_chapter_overrides,
    each mapped to its class. Falls back to authorship.default_class for units
    without an explicit override (there are none here since the map defines the
    list). Returns [(unit_id, class)]."""
    authorship = cfg.get("authorship", {}) or {}
    default_class = authorship.get("default_class", "C")
    # Prefer the canonical ordered units[] list; fall back to per_chapter_overrides.
    units_field = cfg.get("units")
    if isinstance(units_field, list) and units_field:
        out = []
        for item in units_field:
            if isinstance(item, dict) and item.get("id"):
                cls = item.get("class")
                out.append((str(item["id"]), cls if cls in ("A", "B", "C") else default_class))
            elif isinstance(item, str):
                out.append((item, default_class))
        if out:
            return out
    overrides = authorship.get("per_chapter_overrides", {}) or {}
    units = []
    # dict preserves insertion order (Python 3.7+); JSON load preserves file order.
    for unit_id, cls in overrides.items():
        cls = cls if cls in ("A", "B", "C") else default_class
        units.append((str(unit_id), cls))
    return units


def render(template: str, *, unit_id, cls, order, total, prev_id, next_id,
           unit_noun) -> str:
    return template.format(
        unit_id=unit_id,
        class_label=CLASS_LABEL.get(cls, cls),
        order=order,
        total=total,
        prev_id=prev_id,
        next_id=next_id,
        unit_noun=unit_noun,
        unit_noun_lower=unit_noun.lower(),
        unit_noun_cap=unit_noun.capitalize(),
        date=datetime.now(timezone.utc).strftime("%Y-%m-%d"),
    )


def write_template_reference(contracts_dir: Path, template: str) -> None:
    """Drop a _TEMPLATE.md documenting the contract format (idempotent)."""
    ref = contracts_dir / "_TEMPLATE.md"
    if ref.exists():
        return
    ref.write_text(template, encoding="utf-8")
    print(f"  wrote {ref.name}")


def main() -> int:
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

    ap = argparse.ArgumentParser(
        description="Idempotent per-unit contract-stub generator (BOOKSMITH).")
    ap.add_argument("--config", required=True, help="Path to book_config.json.")
    ap.add_argument("--force", action="store_true",
                    help="Overwrite existing contract stubs (default: skip).")
    ap.add_argument("--root", help="Override the workspace root "
                                   "(default: book_workspace/<slug>/).")
    ap.add_argument("--only", help="Only (re)generate the stub for this unit_id.")
    args = ap.parse_args()

    config_path = Path(args.config)
    if not config_path.exists():
        print(f"[ERROR] config not found: {config_path}", file=sys.stderr)
        return 2
    try:
        cfg = load_config(config_path)
    except (json.JSONDecodeError, OSError) as exc:
        print(f"[ERROR] could not parse config {config_path}: {exc}", file=sys.stderr)
        return 2

    unit_noun = (cfg.get("voice", {}) or {}).get("unit_noun", "chapter")
    units = derive_units(cfg)
    if not units:
        print("[ERROR] no units found. book_config.authorship.per_chapter_overrides "
              "must list the seed units (unit_id -> class).", file=sys.stderr)
        return 2

    root = workspace_root(cfg, config_path, args.root)
    contracts_dir = root / "contracts"
    contracts_dir.mkdir(parents=True, exist_ok=True)

    prose_template = load_template()
    write_template_reference(contracts_dir, prose_template)

    total = len(units)
    ids = [u for (u, _) in units]
    written = skipped = 0

    for i, (unit_id, cls) in enumerate(units):
        if args.only and unit_id != args.only:
            continue

        prev_id = ids[i - 1] if i > 0 else "(none)"
        next_id = ids[i + 1] if i < total - 1 else "(none)"

        if cls == "A":
            template = DEFAULT_OUTLINE_TEMPLATE
            filename = f"{unit_id}_outline.md"
        else:
            template = prose_template
            filename = f"{unit_id}.md"

        content = render(template, unit_id=unit_id, cls=cls, order=i + 1,
                         total=total, prev_id=prev_id, next_id=next_id,
                         unit_noun=unit_noun)

        path = contracts_dir / filename
        if path.exists() and not args.force:
            print(f"  skip  {filename} (exists; use --force to overwrite)")
            skipped += 1
            continue
        path.write_text(content, encoding="utf-8")
        print(f"  wrote {filename}  [class {cls}]")
        written += 1

    print()
    print(f"Summary: {written} contract(s) written, {skipped} skipped "
          f"into {contracts_dir}")
    print(f"Units ({unit_noun}s): {total}  |  "
          f"classes: " + ", ".join(f"{u}={c}" for u, c in units))
    print("Class A -> *_outline.md (outline only; manuscript stays empty).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
